[package]
name = "review-bench"
version = "0.0.0"
edition = "2024"
[workspace]
[dependencies]
dssim-core = { path = "../../dssim-core" }
imgref = "=1.12.3"
rgb = "=0.8.53"
[[bin]]
name = "review-bench"
path = "bench.rs"
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 16
panic = "abort"

[[bin]]
name = "parity"
path = "parity.rs"

[[bin]]
name = "memory"
path = "memory.rs"

[[bin]]
name = "score"
path = "score.rs"

[[bin]]
name = "borrowed"
path = "borrowed.rs"
